### ISSUE TITLE
[BUG]: Most recent PR #235 breaks `jekyll serve`

### ISSUE THREAD

**Issue by yardasol** [arfc/arfc.github.io#239]
## I'm submitting a ...
  - [x] bug report
  - [ ] feature request
  - [ ] question

## Expected Behavior
Running `jekyll serve` from the base directory of the repo launches the website locally.

## Actual Behavior
The website fails to build due to a missing key.

Here's the full terminal output:
```
Configuration file: /home/ooblack/projects/arfc.github.io/_config.yml
            Source: /home/ooblack/projects/arfc.github.io
       Destination: /home/ooblack/projects/arfc.github.io/_site
 Incremental build: disabled. Enable with --incremental
      Generating... 
Traceback (most recent call last):
	27: from /home/ooblack/gems/bin/jekyll:23:in `<main>'
	26: from /home/ooblack/gems/bin/jekyll:23:in `load'
	25: from /home/ooblack/gems/gems/jekyll-4.2.1/exe/jekyll:15:in `<top (required)>'
	24: from /home/ooblack/gems/gems/mercenary-0.4.0/lib/mercenary.rb:21:in `program'
	23: from /home/ooblack/gems/gems/mercenary-0.4.0/lib/mercenary/program.rb:44:in `go'
	22: from /home/ooblack/gems/gems/mercenary-0.4.0/lib/mercenary/command.rb:221:in `execute'
	21: from /home/ooblack/gems/gems/mercenary-0.4.0/lib/mercenary/command.rb:221:in `each'
	20: from /home/ooblack/gems/gems/mercenary-0.4.0/lib/mercenary/command.rb:221:in `block in execute'
	19: from /home/ooblack/gems/gems/jekyll-4.2.1/lib/jekyll/commands/serve.rb:86:in `block (2 levels) in init_with_program'
	18: from /home/ooblack/gems/gems/jekyll-4.2.1/lib/jekyll/command.rb:91:in `process_with_graceful_fail'
	17: from /home/ooblack/gems/gems/jekyll-4.2.1/lib/jekyll/command.rb:91:in `each'
	16: from /home/ooblack/gems/gems/jekyll-4.2.1/lib/jekyll/command.rb:91:in `block in process_with_graceful_fail'
	15: from /home/ooblack/gems/gems/jekyll-4.2.1/lib/jekyll/commands/build.rb:36:in `process'
	14: from /home/ooblack/gems/gems/jekyll-4.2.1/lib/jekyll/commands/build.rb:65:in `build'
	13: from /home/ooblack/gems/gems/jekyll-4.2.1/lib/jekyll/command.rb:28:in `process_site'
	12: from /home/ooblack/gems/gems/jekyll-4.2.1/lib/jekyll/site.rb:78:in `process'
	11: from /home/ooblack/gems/gems/jekyll-4.2.1/lib/jekyll/site.rb:181:in `read'
	10: from /home/ooblack/gems/gems/jekyll-4.2.1/lib/jekyll/reader.rb:19:in `read'
	 9: from /home/ooblack/gems/gems/jekyll-4.2.1/lib/jekyll/readers/data_reader.rb:22:in `read'
	 8: from /home/ooblack/gems/gems/jekyll-4.2.1/lib/jekyll/readers/data_reader.rb:40:in `read_data_to'
	 7: from /home/ooblack/gems/gems/jekyll-4.2.1/lib/jekyll/readers/data_reader.rb:40:in `each'
	 6: from /home/ooblack/gems/gems/jekyll-4.2.1/lib/jekyll/readers/data_reader.rb:48:in `block in read_data_to'
	 5: from /home/ooblack/gems/gems/jekyll-4.2.1/lib/jekyll/readers/data_reader.rb:70:in `read_data_file'
	 4: from /home/ooblack/gems/gems/safe_yaml-1.0.5/lib/safe_yaml/load.rb:157:in `load_file'
	 3: from /home/ooblack/gems/gems/safe_yaml-1.0.5/lib/safe_yaml/load.rb:157:in `open'
	 2: from /home/ooblack/gems/gems/safe_yaml-1.0.5/lib/safe_yaml/load.rb:157:in `block in load_file'
	 1: from /home/ooblack/gems/gems/safe_yaml-1.0.5/lib/safe_yaml/load.rb:143:in `load'
/home/ooblack/gems/gems/safe_yaml-1.0.5/lib/safe_yaml/load.rb:143:in `parse': (/home/ooblack/projects/arfc.github.io/_data/alumni.yml): did not find expected key while parsing a block mapping at line 408 column 3 (Psych::SyntaxError)
```
The referenced `.yml` file was changed in #235. I tested the previous version of the code from #233 and did not run into this bug. My suspicion is that there's some issue with the use of commas in that throws off the parser. 

## Steps to Reproduce the Problem

  1. Clone this repo and make sure [you get all the necessary dependencies](https://arfc.github.io/manual/guides/website)
  1. Move the the base directory of the `source` branch of the repo
  1. Run `jekyll serve`

## Specifications

  - Version: Jekyll 4.2.1, Ruby 2.7.2p137
  - Platform: Ubuntu 21.04

## How can this issue be closed?
This issue can be closed when a PR that fixes the bug exists.

**Comment by nsryan2** [comment]
Thanks for bringing this to up! I will say, I am not experiencing the same issue on my end. I'll check to see exactly what the changes in #235 are that might lead to this.

**Comment by nsryan2** [comment]
Unrelated, but I recently updated all of my jekyll stuff (it doesn't seem like that retired anything relavent to the site, but just something to note if you haven't had need to update all your dependencies recently).

**Comment by munkm** [comment]
I will confirm that I encountered the same issue trying to build locally as @yardasol . I am using jekyll 4.2.0 and ruby-2.7.2 .
