### ISSUE TITLE
Invalid byte sequence error when building on Ubuntu 22.04

### ISSUE THREAD

**Issue by yardasol** [arfc/arfc.github.io#257]
This repository's issues are reserved for feature requests, and bug reports, and questions.

## I'm submitting a ...
  - [x] bug report
  - [ ] feature request
  - [ ] question

## Expected Behavior
The website builds without issue

## Actual Behavior
```
$ jekyll serve --trace
Configuration file: /home/ooblack/projects/arfc.github.io/_config.yml
            Source: /home/ooblack/projects/arfc.github.io
       Destination: /home/ooblack/projects/arfc.github.io/_site
 Incremental build: disabled. Enable with --incremental
      Generating... 
    Jekyll-scholar: Option `use_raw_bibtex_entry` is no longer supported
  Liquid Exception: invalid byte sequence in US-ASCII in /home/ooblack/projects/arfc.github.io/_layouts/publications.html
/home/ooblack/gems/gems/bibtex-ruby-6.0.0/lib/bibtex/lexer.rb:220:in `scan_until': invalid byte sequence in US-ASCII (ArgumentError)
	from /home/ooblack/gems/gems/bibtex-ruby-6.0.0/lib/bibtex/lexer.rb:220:in `parse_meta'
	from /home/ooblack/gems/gems/bibtex-ruby-6.0.0/lib/bibtex/lexer.rb:180:in `analyse'
	from bibtex.y:110:in `parse'
	from /home/ooblack/gems/gems/bibtex-ruby-6.0.0/lib/bibtex/bibliography.rb:67:in `parse'
	from /home/ooblack/gems/gems/jekyll-scholar-7.0.0/lib/jekyll/scholar/utilities.rb:193:in `bibliography'
	from /home/ooblack/gems/gems/jekyll-scholar-7.0.0/lib/jekyll/scholar/utilities.rb:219:in `entries'
	from /home/ooblack/gems/gems/jekyll-scholar-7.0.0/lib/jekyll/scholar/utilities.rb:838:in `cited_entries'
	from /home/ooblack/gems/gems/jekyll-scholar-7.0.0/lib/jekyll/scholar/tags/bibliography.rb:20:in `render'
	from /home/ooblack/gems/gems/liquid-4.0.3/lib/liquid/block_body.rb:103:in `render_node_to_output'
	from /home/ooblack/gems/gems/liquid-4.0.3/lib/liquid/block_body.rb:91:in `render'
	from /home/ooblack/gems/gems/liquid-4.0.3/lib/liquid/template.rb:208:in `block in render'
	from /home/ooblack/gems/gems/liquid-4.0.3/lib/liquid/template.rb:242:in `with_profiling'
	from /home/ooblack/gems/gems/liquid-4.0.3/lib/liquid/template.rb:207:in `render'
	from /home/ooblack/gems/gems/liquid-4.0.3/lib/liquid/template.rb:220:in `render!'
	from /home/ooblack/gems/gems/jekyll-4.2.2/lib/jekyll/liquid_renderer/file.rb:39:in `block (3 levels) in render!'
	from /home/ooblack/gems/gems/jekyll-4.2.2/lib/jekyll/liquid_renderer/file.rb:59:in `measure_counts'
	from /home/ooblack/gems/gems/jekyll-4.2.2/lib/jekyll/liquid_renderer/file.rb:38:in `block (2 levels) in render!'
	from /home/ooblack/gems/gems/jekyll-4.2.2/lib/jekyll/liquid_renderer/file.rb:63:in `measure_bytes'
	from /home/ooblack/gems/gems/jekyll-4.2.2/lib/jekyll/liquid_renderer/file.rb:37:in `block in render!'
	from /home/ooblack/gems/gems/jekyll-4.2.2/lib/jekyll/liquid_renderer/file.rb:70:in `measure_time'
	from /home/ooblack/gems/gems/jekyll-4.2.2/lib/jekyll/liquid_renderer/file.rb:36:in `render!'
	from /home/ooblack/gems/gems/jekyll-4.2.2/lib/jekyll/renderer.rb:131:in `render_liquid'
	from /home/ooblack/gems/gems/jekyll-4.2.2/lib/jekyll/renderer.rb:194:in `render_layout'
	from /home/ooblack/gems/gems/jekyll-4.2.2/lib/jekyll/renderer.rb:163:in `place_in_layouts'
	from /home/ooblack/gems/gems/jekyll-4.2.2/lib/jekyll/renderer.rb:93:in `render_document'
	from /home/ooblack/gems/gems/jekyll-4.2.2/lib/jekyll/renderer.rb:63:in `run'
	from /home/ooblack/gems/gems/jekyll-4.2.2/lib/jekyll/site.rb:547:in `render_regenerated'
	from /home/ooblack/gems/gems/jekyll-4.2.2/lib/jekyll/site.rb:539:in `block in render_pages'
	from /home/ooblack/gems/gems/jekyll-4.2.2/lib/jekyll/site.rb:538:in `each'
	from /home/ooblack/gems/gems/jekyll-4.2.2/lib/jekyll/site.rb:538:in `render_pages'
	from /home/ooblack/gems/gems/jekyll-4.2.2/lib/jekyll/site.rb:211:in `render'
	from /home/ooblack/gems/gems/jekyll-4.2.2/lib/jekyll/site.rb:80:in `process'
	from /home/ooblack/gems/gems/jekyll-4.2.2/lib/jekyll/command.rb:28:in `process_site'
	from /home/ooblack/gems/gems/jekyll-4.2.2/lib/jekyll/commands/build.rb:65:in `build'
	from /home/ooblack/gems/gems/jekyll-4.2.2/lib/jekyll/commands/build.rb:36:in `process'
	from /home/ooblack/gems/gems/jekyll-4.2.2/lib/jekyll/command.rb:91:in `block in process_with_graceful_fail'
	from /home/ooblack/gems/gems/jekyll-4.2.2/lib/jekyll/command.rb:91:in `each'
	from /home/ooblack/gems/gems/jekyll-4.2.2/lib/jekyll/command.rb:91:in `process_with_graceful_fail'
	from /home/ooblack/gems/gems/jekyll-4.2.2/lib/jekyll/commands/serve.rb:86:in `block (2 levels) in init_with_program'
	from /home/ooblack/gems/gems/mercenary-0.4.0/lib/mercenary/command.rb:221:in `block in execute'
	from /home/ooblack/gems/gems/mercenary-0.4.0/lib/mercenary/command.rb:221:in `each'
	from /home/ooblack/gems/gems/mercenary-0.4.0/lib/mercenary/command.rb:221:in `execute'
	from /home/ooblack/gems/gems/mercenary-0.4.0/lib/mercenary/program.rb:44:in `go'
	from /home/ooblack/gems/gems/mercenary-0.4.0/lib/mercenary.rb:21:in `program'
	from /home/ooblack/gems/gems/jekyll-4.2.2/exe/jekyll:15:in `<top (required)>'
	from /home/ooblack/gems/bin/jekyll:25:in `load'
	from /home/ooblack/gems/bin/jekyll:25:in `<main>'

```
I initially thought that Jekyll was having trouble rendering the raw bibtex ([`use_raw_bibtex_entry` is no longer supported](https://github.com/inukshuk/jekyll-scholar/pull/274)), however after downgrading both `jekyll` and `jekyll-scholar` to versions that would support this option, I ran into the same issue.

## Steps to Reproduce the Problem

  1. Checkout [yardasol-patch-1](https://github.com/arfc/arfc.github.io/tree/yardasol-patch-1)
  1. Run `jekyll serve`

## Specifications

  - Version: 
    - `jekyll 4.2.2`
    - `ruby 3.0.2p107`
    - `gem 3.3.5`
    - `GNU Make 4.3`
    - `gcc 11.2.0`
  - Platform: Ubuntu 22.04

## How can this issue be closed?
This issue can be closed when a PR exists that makes changes that allow the website to build.

**Comment by munkm** [comment]
I'll try it when I get a chance!

**Comment by yardasol** [comment]
@munkm bump

**Comment by yardasol** [comment]
This is relevant to #247

**Comment by munkm** [comment]
On my machine I am able to build and preview the site. Here are the commands I used: 

`$rake generate` 

```
Configuration file: /Users/madicken/repos/arfc/arfc.github.io/_config.yml
    Jekyll-scholar: Option `use_raw_bibtex_entry` is no longer supported
```

`$jekyll serve`

```
Configuration file: /Users/madicken/repos/arfc/arfc.github.io/_config.yml
            Source: /Users/madicken/repos/arfc/arfc.github.io
       Destination: /Users/madicken/repos/arfc/arfc.github.io/_site
 Incremental build: disabled. Enable with --incremental
      Generating...
    Jekyll-scholar: Option `use_raw_bibtex_entry` is no longer supported
                    done in 3.703 seconds.
 Auto-regeneration: enabled for '/Users/madicken/repos/arfc/arfc.github.io'
    Server address: http://127.0.0.1:4000/
  Server running... press ctrl-c to stop.
```

I am using rvm to manage ruby versions. I haven't updated ruby in a while, so I'm using ruby-2.7.2, rake version 13.0.1, and jekyll 4.2.0
